### ISSUE TITLE
Fix Find Garages by IP address

### ISSUE THREAD

**Issue by Codehackerone** [Codehackerone/parkify#13]
**Describe the bug**
Find Garages using IP Adress doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://parkify-web.herokuapp.com/garage/find/
2. Click on 'Find by IP'
3. 'Internal Server Error' Appears.

**Expected behaviour**
Find the nearest garage and show the location on the map.

**Comment by ap1809** [comment]
I wanna work on this issue

**Comment by Codehackerone** [comment]
Sure. Do tell me if you need any help with the setup. :)

**Comment by Codehackerone** [comment]
Done
