### ISSUE TITLE
Redesign all booking page

### ISSUE THREAD

**Issue by Codehackerone** [Codehackerone/parkify#24]
- Can be found at /users/bookings
- Use vanilla html/css/js and bootstrap to make it look better

**Comment by codegoggins** [comment]
Hey ! @Codehackerone 
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help.

**Comment by Villain45** [comment]
Would like to work on this

**Comment by Codehackerone** [comment]
Done
