### ISSUE TITLE
Redesign navbar

### ISSUE THREAD

**Issue by Codehackerone** [Codehackerone/parkify#25]
Use vanilla html/css/js with bootstrap to make the navbar

**Comment by codegoggins** [comment]
Hey ! @Codehackerone 
This is my very first time contributing to open source. . I would like to contribute in adding some designs here.
I am new to Open Source , it would be great if you could help.

**Comment by ahmedsilat44** [comment]
Hey @Codehackerone this is my first time participating in hacktoberfest, and I am also new to open source. I would like to do this task. If it is available please assign it to me. Thanks 😄

**Comment by sunidhisachan** [comment]
Hey @Codehackerone , I can do this . Please assign this to me.

**Comment by InsightCracker** [comment]
I've gone through the website.. it's really awesome.

This isn't actually my first time contributing to open source. I promise to give it my all nd make it standout.

**Comment by manav-06** [comment]
Hi @Codehackerone I would like to work on this

**Comment by mustafaazad03** [comment]
Hello @Codehackerone ,

I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me.

**Comment by kashifumair125** [comment]
hey! @Codehackerone could you assign this to me i would like to work on this .

**Comment by Codehackerone** [comment]
Hey, @Mustafa-Azad025 I would like you to work on this issue. And others, thank you for your interest. Please look for other issues in this project. I'll add tons of them this weekend, and they will be beginner friendly. 😊

**Comment by Codehackerone** [comment]
@Mustafa-Azad025 Please hold off your PR till the 1st of October

**Comment by mustafaazad03** [comment]
Thanks @Codehackerone ,
I will raise PR on 1st or 2nd Oct

**Comment by Codehackerone** [comment]
@Mustafa-Azad025 any updates?

**Comment by mustafaazad03** [comment]
I will raise PR on 3 or 4 Oct Will it be Ok ??

**Comment by Codehackerone** [comment]
This is a small issue, can you try finishing it by tomorrow EOD?

**Comment by mustafaazad03** [comment]
Ok I will do that 🙂

**Comment by mustafaazad03** [comment]
Hey @Codehackerone ,
I have made navbar with tailwind as bootstrap components are very basic and include in many websites.
I hope you like the navbar .

**Comment by Codehackerone** [comment]
Share a ss here

**Comment by mustafaazad03** [comment]
![image](https://user-images.githubusercontent.com/97380192/193444759-551fd51b-6203-441d-9d8c-3d154c9c1bdb.png)

**Comment by Codehackerone** [comment]
PR #35 Merged
