### ISSUE TITLE
Redesign dashboard

### ISSUE THREAD

**Issue by Codehackerone** [Codehackerone/parkify#26]
- Think of how we can improve the way the dashboard looks.
- Can we add some new features to the screen
- suggest some ideas

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ?
Where can I see the dashboard design and how should I implement ideas if any ?
I am new to Open Source , it would be great if you could help.

**Comment by InsightCracker** [comment]
I've gone through the website...

Can I fix this??

**Comment by Codehackerone** [comment]
Hey @codegoggins. I know first-time contributions can be tough and confusing. I'll help you out, but please do not comment the same thing on every issue and project. I suggest you go through the project, follow the steps mentioned in the readme file and then comment describing how you want to do it. Hope this helps!! 😀

**Comment by InsightCracker** [comment]
Thanks for this

**Comment by Villain45** [comment]
Would like to work on this

**Comment by Codehackerone** [comment]
Sure
