### ISSUE TITLE
Outdated bookings visible when logging in, disappears when reloaded

### ISSUE THREAD

**Issue by Codehackerone** [Codehackerone/parkify#32]
**Describe the bug**
Outdated bookings are visible when logging in and disappear when reloaded

**To Reproduce**
Steps to reproduce the behaviour:

1. Complete a slot booking
2. After the booking expires, signout and relogin
3. The previous booking will be visible as the current Booking

**Expected behaviour**
The booking should be expected as completed

**Additional context**
Rethink and update the `complete booking` functionality.

**Comment by ighmaZ** [comment]
@Codehackerone would love to take on this

**Comment by Codehackerone** [comment]
Sure... Can you tell me how you want to approach this?

**Comment by ap1809** [comment]
I went through the code, and i noticed the 'updateBooking' logic is not implemented correctly. Can I work on this?

**Comment by Codehackerone** [comment]
Okay sure

**Comment by Codehackerone** [comment]
PR #37

**Comment by Codehackerone** [comment]
Done
