### ISSUE TITLE
Add LEARN.md

### ISSUE THREAD

**Issue by ericdrosado** [Codehackerone/parkify#4]
`Learn` repos should have a LEARN.md file to teach another student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn. 

Since your project is large, consider just teaching a certain tool or implementation that your project utilizes.

**Comment by Codehackerone** [comment]
As this is kind of a huge task, can it be done at the very end? And some issues depend on LEARN.md, so can I create a blank one for now and move on with the rest of the issues?

**Comment by ericdrosado** [comment]
> kind of a huge task

I completely understand. It is a big ask given how large your codebase is. 

I would recommend not worrying about this for your submission. You can submit a `collaborate` repo to start, and if you decide you want to teach students how to write portions of your code you can add LEARN.md later. 

I'll go ahead and close this issue. 😄
