### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericdrosado** [Codehackerone/parkify#6]
A README is often the first item a visitor will see when visiting your repository. We recommend that your README includes information on:
* What the project does
* Why the project is useful
* How users can get started with the project
  * Explain to users that there is a LEARN.md
  * How to [contribute to your project](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)
* Mention your code of conduct
* Who maintains and contributes to the project

You already have some great setup content. 😄

**Comment by Codehackerone** [comment]
Readme updated
