### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by ericdrosado** [Codehackerone/parkify#7]
Other than GitHub Topics, your description will be the primary way of catching the users eyes. Your repo description should be clear and concise. Ask yourself:

* In one sentence, how do I convey what my repo does?
* What type of users am I interested in attracting to my repo?
* If I was a user, what words or phrases might spark my interest?

**Comment by Codehackerone** [comment]
Repo Description Updated

**Comment by ericdrosado** [comment]
@Codehackerone is there a way we can clarify: 

> A simple way to solve your complex parking issues. 

In my opinion, I see `complex parking issues`, and I'm not sure what exactly that means. The README doesn't explain it to me nor does the first page of the website. I can guess what it means, but you should be clear, about what that means.

For example, does it mean:
* You'll help me find a parking space? 
* Will you help me save money on a parking space? 
* Do you help me negotiate a price for a private parking space? 

The more clarity you can bring, the more you'll attract users.

**Comment by Codehackerone** [comment]
`Hasslefree way of booking your parking space with easy cancellations and timeline extensions`. Will this be okay?

**Comment by ericdrosado** [comment]
That is perfect!

**Comment by Codehackerone** [comment]
Done

**Comment by ericdrosado** [comment]
🔥  I would just add a period after the sentence before the Node friendly bit. Once that is done, feel free to close this issue.
